services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: castelo-io-database
      POSTGRES_USER: castelo-io
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'