services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: castelo-io-database
      POSTGRES_USER: castelo-io
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
volumes:
  mongo: {}