name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up JDK 23 to match the build.gradle config
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: "23" # Version matching your build.gradle
        distribution: "temurin"

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Set up Gradle Wrapper for the build process
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # Build with the Gradle wrapper
    - name: Build with Gradle Wrapper
      run: ./gradlew build --no-daemon --scan

    # Test the application (will use Gradle's `test` task)
    - name: Run Tests
      run: ./gradlew test --no-daemon --info

    # Generate a dependency graph for submission
  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Set up JDK 23
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: "23"
        distribution: "temurin"

    # Generates and submits a dependency graph
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
